export const FETCHED_AUTH = "FETCHED_AUTH";
export const FETCHED_MY_PROFILE = "FETCHED_MY_PROFILE";
export const REQUESTED_MY_PROFILE = "REQUESTED_MY_PROFILE";
export const REQUESTED_MY_PROFILE_SUCCEEDED = "REQUESTED_MY_PROFILE_SUCCEEDED";
export const FETCHED_BOOKS = "FETCHED_BOOKS";
export const FETCHED_SEARCH_BOOKS = "FETCHED_SEARCH_BOOKS";
export const FETCHED_BOOK = "FETCHED_BOOK";
export const REQUESTED_BOOKS = "REQUESTED_BOOKS";
export const REQUESTED_BOOKS_SUCCEEDED = "REQUESTED_BOOKS_SUCCEEDED";
export const REQUESTED_SEARCH_BOOKS = "REQUESTED_SEARCH_BOOKS";
export const REQUESTED_SEARCH_BOOKS_SUCCEEDED =
  "REQUESTED_SEARCH_BOOKS_SUCCEEDED";
export const REQUESTED_BOOK = "REQUESTED_BOOK";
export const REQUESTED_BOOK_SUCCEEDED = "REQUESTED_BOOK_SUCCEEDED";
export const FETCHED_ADD_BOOK = "FETCHED_ADD_BOOK";
