// auth and profile
export const FETCHED_AUTH = "FETCHED_AUTH";
export const FETCHED_MY_PROFILE = "FETCHED_MY_PROFILE";
export const REQUESTED_MY_PROFILE = "REQUESTED_MY_PROFILE";
export const REQUESTED_MY_PROFILE_SUCCEEDED = "REQUESTED_MY_PROFILE_SUCCEEDED";
export const UPDATE_AVATAR = "UPDATE_AVATAR";
export const UPDATE_INFO = "UPDATE_INFO";
export const REQUESTED_REFRESH_TOKEN = "REQUESTED_REFRESH_TOKEN";
export const REQUESTED_MY_PROFILE_ERROR = "REQUESTED_MY_PROFILE_ERROR";
export const REQUESTED_TOKEN = "REQUESTED_TOKEN";

//book and books
export const FETCHED_BOOKS = "FETCHED_BOOKS";
export const FETCHED_SEARCH_BOOKS = "FETCHED_SEARCH_BOOKS";
export const FETCHED_BOOK = "FETCHED_BOOK";
export const REQUESTED_BOOKS = "REQUESTED_BOOKS";
export const REQUESTED_BOOKS_SUCCEEDED = "REQUESTED_BOOKS_SUCCEEDED";
export const REQUESTED_SEARCH_BOOKS = "REQUESTED_SEARCH_BOOKS";
export const REQUESTED_SEARCH_BOOKS_SUCCEEDED =
  "REQUESTED_SEARCH_BOOKS_SUCCEEDED";
export const REQUESTED_BOOK = "REQUESTED_BOOK";
export const REQUESTED_BOOK_SUCCEEDED = "REQUESTED_BOOK_SUCCEEDED";
export const FETCHED_ADD_BOOK = "FETCHED_ADD_BOOK";
export const UPDATE_BOOK = "UPDATE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";
export const REQUESTED_BOOK_ERROR = "REQUESTED_BOOK_ERROR";
export const REQUESTED_BOOKS_ERROR = "REQUESTED_BOOKS_ERROR";
export const REQUESTED_SEARCH_BOOKS_ERROR = "REQUESTED_SEARCH_BOOKS_ERROR";

// author
export const FETCHED_ADD_AUTHOR = "FETCHED_ADD_AUTHOR";
export const FETCHED_SEARCH_AUTHORS = "FETCHED_SEARCH_AUTHORS";
export const REQUESTED_SEARCH_AUTHORS = "REQUESTED_SEARCH_AUTHORS";
export const REQUESTED_SEARCH_AUTHORS_SUCCEEDED =
  "REQUESTED_SEARCH_AUTHORS_SUCCEEDED";
export const FETCHED_AUTHOR = "FETCHED_AUTHOR";
export const REQUESTED_AUTHOR = "REQUESTED_AUTHOR";
export const REQUESTED_AUTHOR_SUCCEEDED = "REQUESTED_AUTHOR_SUCCEEDED";
export const REQUESTED_AUTHOR_ERROR = "REQUESTED_AUTHOR_ERROR";
export const REQUESTED_SEARCH_AUTHORS_ERROR = "REQUESTED_SEARCH_AUTHORS_ERROR";
export const POST_SEARCH_VALUE = "POST_SEARCH_VALUE";

//notification
export const REQUESTED_NOTIFICATION_TRUE = "REQUESTED_NOTIFICATION_TRUE";
export const REQUESTED_NOTIFICATION_FALSE = "REQUESTED_NOTIFICATION_FALSE";

//order
export const FETCHED_CREATE_ORDER = "FETCHED_CREATE_ORDER";

//other
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_MESSAGE = "SET_MESSAGE";
export const GET_STATUS_CODE = "GET_STATUS_CODE";
